name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}

            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}

            docker build --build-arg DATABASE_NAME=${DATABASE_NAME} \
              --build-arg DATABASE_USER=${DATABASE_USER } \
              --build-arg DATABASE_PASSWORD=${DATABASE_PASSWORD} \
              -t $DOCKER_IMAGE_NAME:latest .

            docker run -p 8000:80 -d ${{ secrets.DOCKER_IMAGE_NAME }}:latest


            docker run --name postgres-container \
              -e POSTGRES_PASSWORD=${DATABASE_PASSWORD} \
              -e DATABASE_NAME=${DATABASE_NAME} \
              -e POSTGRES_USER=${DATABASE_USER} \
              -p 5432:5432 \
              -d $DOCKER_IMAGE_NAME:latest
